[project]
name = "curso-python-flask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "ipdb>=0.13.13",
    "ipython>=9.5.0",
    "setuptools>=80.9.0",
]
